
# Site settings
title: "Tanvir Hossain"
email: tanvir@ku.edu

include:
  - _pages

exclude:
  - PROJECT_STRUCTURE.md

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
    
plugins:
  - jekyll-sitemap